### ISSUE TITLE
Run IB Gateway instead of TWS?

### ISSUE THREAD

**Issue by acowlikeobject** [pehowell/docker-ib#1]
So, this is a bit embarrassing... but when I run the container, IB TWS starts listening on port 7497 (paper account) and nothing on 4001/4002.  Is there a way to run IB Gateway instead?  From the title of the repo and your use of port 4001, I'm sure there is :), but I can't seem to figure it out.

**Comment by pehowell** [comment]
So this container is leveraging Arch Linux's AUR packages that is community maintained, and they have elected to use TWS.  However, I don't know of a good reason to switch to the IB Gateway.  You can change the port that TWS is using to any port you want.

The easiest way is to log into TWS on your desktop, using the desktop app downloaded from Interactive Brokers.  Change all the settings you want, including enabling the API port and setting the port number to 4001, then make sure to choose to [store settings to server](https://ibkr.info/article/2282).  When you create a new container from the docker image and run it, it should pull down these settings after authenticating.

The other way is to copy the settings xml file that TWS creates into the docker container.    But I would recommend using the server to store the settings.

**Comment by acowlikeobject** [comment]
Thanks. The only reason I prefer IB Gateway is the ability to run for days on end.  But, it seems like IB Controller's config has a way to gracefully restart TWS at a pre-specified time daily, so perhaps that obviates my need for Gateway.

**Comment by acowlikeobject** [comment]
(Although, you may consider changing the title of your README and repo to "Headless IB TWS Docker image" instead of "Headless IB Gateway Docker image ".)

**Comment by pehowell** [comment]
Thanks for pointing that out! I'll update the text to reflect it's running TWS and not IB Gateway.
